### PR TITLE
Add MANIFEST.in

### PR DESCRIPTION
**Pull request by bollwyvl**
Hi, thanks for the work!

I'm looking to get sqlalchemy-jsonapi [built for conda](https://github.com/conda-forge/staged-recipes/pull/1942) with the conda-forge community. As part of that, we try to make sure that the distributed packages clearly communicate the rights that a user has, which mainly takes the form of including the license file in the distributed package (not just the name of the license in the metadata).

In the spirit of [this guide](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/), this adds the requisite `fix MANIFEST.in` commit!

Of course, you might want to include other things, too, (README?) and I'm not sure if a 4.0.9 is forthcoming, but since the 4.x line is what is currently distributed, I figured it was worth starting here!

### CODE REVIEW

**Comment by jakirkham** [comment]
Could someone please take a look at this?

**Comment by deryckh** [comment]
Hi @bollwyvl and @jakirkham. I'm helping @ColtonProvias get reviews done and PRs merged. Can you please retarget to master and also include the README? Then I'd be happy to approve and merge it.

**Comment by bollwyvl** [comment]
Eek... I'm going to start over on another PR!

**Comment by jakirkham** [comment]
Please see PR ( https://github.com/ColtonProvias/sqlalchemy-jsonapi/pull/36 ).

**Pull request closed without merging**
